### PR TITLE
Fix tinymce widget  for modeltranslation tabs

### PR DESCRIPTION
**Pull request by rddimon**

### CODE REVIEW

**Comment by Natim** [comment]
Hello @rddimon Thanks for your work on this. Do you mind adding your name in the CONTRIBUTORS file? https://github.com/aljosa/django-tinymce/blob/master/CONTRIBUTORS.rst

**Comment by Natim** [comment]
Would you mind rebasing your branch as well?

**Comment by rddimon** [comment]
Rebasing done. Update CONTRIBUTORS.
Would you like to check?

**Comment by Natim** [comment]
Thanks.

**Pull request merged**
