### PR TITLE
[Feat] refactor all tinymce module

### PR DESCRIPTION
**Pull request by vanadium23**
Hello, fellows.

Long ago I've created task #160 to switch this module to new tinymce, and mostly I just want to entire refactor this old code.
Some results:
* switch to minified cdn version of tinymce (no need in bunch of static)
* remove almost all views from tinymce (especially, gzip_compressor)
* add some base selenium tests

### CODE REVIEW

**Comment by vanadium23** [comment]
@Natim can you check this please, I've divided commits and almost all 90k is in first commit (:

**Comment by Natim** [comment]
How do you plan on doing it? The diff is totally unreadable

**Comment by aljosa** [comment]
- is there a use case where bundling static files is required?
- do custom plugins work w/ cdn version or is local/static bundling required?
- what will stop working after the upgrade?

@vanadium23 @Natim except for the commit which removes static/media files, other diffs per commit are readable

**Comment by Natim** [comment]
> other diffs per commit are readable

Ok thanks for the tip :)

**Comment by Natim** [comment]
Depending on the use case you cannot load files from the CDN (notably use cases where you don't have internet access while using your Django app)

I think the idea is good for some usecases but I feel like this should be a new project and a new way of handling tinymce setup.

**Comment by vanadium23** [comment]
@aljosa
> is there a use case where bundling static files is required?
Only if company is filtering traffic to network, but you can set to local by setting TINYMCE_JS.
> do custom plugins work w/ cdn version or is local/static bundling required?
Yes, they work.
> what will stop working after the upgrade?
Filebrowser, spellchecker, may be other. I think we need some pre-release build. I don't know all usecases, but ask couple of friends to upgrade to unstable version and they say it's fine.

@Natim 
> Depending on the use case you cannot load files from the CDN (notably use cases where you don't have internet access while using your Django app)
Okay, we can put local minified file and add to docs how to change to local version. Is this good? I don't like idea of separate package, that does same thing.

**Comment by aljosa** [comment]
we should release a django-tinymce version w/ tinymce4 support.
the problem seems to be how to define what should be included and how the new version should work.

having CDN url and bundling static files should be supported, we need configuration/settings suggestions.
i wouldn't mind if, by default, CDN is used. it would allow all new users to use tinymce4 w/o any staticfiles/collectstatic/deployment issues.

by default, w/o configuration, it should just work.
we just need a flexible way to allow developers w/ specific requirements to modify tinymce4 location/url and configuration.

**Comment by Natim** [comment]
I guess if people can server tinymce4 from there staticfiles and defaulting to CDN it would be good enough.

**Comment by vanadium23** [comment]
Fair enough, add minified static from tinymce.com for version 4.5.2.
We need to make some shell script for automatic upgrade bundled static.

**Comment by Natim** [comment]
I though we had some script to do so, I also created a script to make sure the encoding of all static files was in UTF-8.

**Comment by vanadium23** [comment]
Okay, may be merge & wait for feedback?

**Comment by vanadium23** [comment]
@Natim @aljosa fellows? (:

**Comment by Natim** [comment]
Do you plan on dropping support for tinymce3 ?

**Comment by aljosa-mohorovic** [comment]
hey @vanadium23, we also need to update the docs and update the readme so that people know that the old version is not supported (and howto install the old version and use a fixed version in requirements.txt).

I would like to try this branch in at least 2 projects before we replace the old, tinymce3 based, version.

I understand that you'd like to push this release asap but it could have unwanted consequences since a lot of people are using the current version.
That would be bad and the complaints would undo the great work you did on supporting tinymce4.

I think the next steps should be:
- [ ] update the readme/docs to reflect the changes. configuration for tinymce4 changed, users should be able to configure django-tinymce using instructions on https://www.tinymce.com/docs/configure/integration-and-setup/
- [ ] figure out if we can release django-tinymce v3.0 (dev/beta/etc.) but when somebody uses `$ pip install django-tinymce` it should install the current v2.x version

**Comment by aljosa-mohorovic** [comment]
@Natim @vanadium23 also, we should figure out the workflow for supporting tinymce3 and tinymce4 until it's clear that support for tinymce3 is no longer required

**Comment by aljosa** [comment]
hey @vanadium23, we also need to update the docs and update the readme so that people know that the old version is not supported (and howto install the old version and use a fixed version in requirements.txt).

I would like to try this branch in at least 2 projects before we replace the old, tinymce3 based, version.

I understand that you'd like to push this release asap but it could have unwanted consequences since a lot of people are using the current version.
That would be bad and the complaints would undo the great work you did on supporting tinymce4.

I think the next steps should be:
- [ ] update the readme/docs to reflect the changes. configuration for tinymce4 changed, users should be able to configure django-tinymce using instructions on https://www.tinymce.com/docs/configure/integration-and-setup/
- [ ] figure out if we can release django-tinymce v3.0 (dev/beta/etc.) but when somebody uses `$ pip install django-tinymce` it should install the current v2.x version

**Comment by aljosa** [comment]
@Natim @vanadium23 also, we should figure out the workflow for supporting tinymce3 and tinymce4 until it's clear that support for tinymce3 is no longer required

**Comment by Natim** [comment]
One way of doing that is to keep the django-tinymce 2.0 branch for tinymce3 and create a django-tinymce 3.0 branch for tinymce 4

**Comment by vanadium23** [comment]
> I understand that you'd like to push this release asap but it could have unwanted consequences since a lot of people are using the current version.

Actually, I only want advices how to make this PR better, but not doing this asap.
Sorry that I'm calling you to often :(

**Comment by aljosa** [comment]
@vanadium23 not a problem, i really appreciate your work and i'm looking forward to this release :-)

**Comment by narfman0** [comment]
Splendid work! Thanks all! I suggest making a new project only supporting 4, especially if using a CDN, and new release on pypi at least. This could be merged without asking many of the above questions, then. Possibly in a single day with no one being broken (with non-trivial configs? shrugs :)). For other users it may be quite a surprise and potential time investment, unless you do the counterintuitive pip hacks of 3.0.0-dev0 and maybe perpetually keep using the special dev string after a version number so people won't get upgraded to a whole new package..? Then you could add a note in the old repo, have everything current on documentation, and no surprise to users. :)

**Comment by vanadium23** [comment]
@narfman0 and fellows, I've decided to switch to new project for not breaking changes with all my refactor.

**Comment by Flimm** [comment]
Let us know what the URL is for the new project.

**Comment by vanadium23** [comment]
https://github.com/vanadium23/django-tinymce-lite

**Comment by Flimm** [comment]
Thanks.

Not to be confused with [`django-tinymce4-lite`](https://pypi.python.org/pypi/django-tinymce4-lite/).

**Pull request closed without merging**
