### PR TITLE
Upgrade to 4.2.4

### PR DESCRIPTION
**Pull request by dani0805**
Upgraded tinymce to version 4.2.4
Extended documentation
set version to 3.0

### CODE REVIEW

**Comment by Natim** [comment]
I created the 2.x branch. Let's merge this and make a release.

**Comment by Natim** [comment]
I have released an hidden django-tinymce===3.0.0 for you to try.

**Comment by Natim** [comment]
Oh I didn't see that you merged in tinymce4

**Comment by dani0805** [comment]
Yep sorry, I saw you worked in master and did not want to wreck your code. If you want I can merge it and the do a pull request on master...

Daniele Bernardini
Intranet Standard GmbH
Ottostr. 3
80333 Munich Germany
Tel: +49 151 22653325
E-Mail: daniele.bernardini@intranetstandard.com

**Pull request merged**
